# vim:ft=ansible:
version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN} 
    environment:
      NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN} 
    image: cachak/nextjs-hello-world:latest

